### ISSUE TITLE
404 not being displayed

### ISSUE THREAD

**Issue by doogthemushroom** [rit-sse/wtf#24]
When entering a link to the website, if it ends in a file extension that is handled by a browser the 404 error will not be displayed even if the item is not actually there.

i.e.

sse.se.rit.edu/a.pdf
sse.se.rit.edu/b.txt
sse.se.rit.edu/c.css

These links result in a blank page on the website instead of a 404.

**Comment by codykrieger** [comment]
That's intentional - static assets are expensive to serve through a Ruby process, so I have a lot of file extensions blacklisted and those requests all go purely through nginx, instead of ever touching the Rails app. Sorry for the confusion.
