### ISSUE TITLE
Publically hosted HTML source is missing a favicon

### ISSUE THREAD

**Issue by nickserv** [rit-sse/wtf#27]
NOTE: I have not actually looked at the source in this repo, as I do not know Rails yet and I have not been working on this repository. I am merely commenting on the source code I can currently view from sse.se.rit.edu.

I've noticed that a small amount of metadata that is generally a good idea to have in HTML pages is missing from the site.

For example:
- ~~`<html lang="en">` (the HTML tag should specify that the page is in English, just to be safe)~~
- ~~`<meta charset="YOUR_ENCODING_HERE">` (specify the character encoding to be safe, as being explicit about this can potentially speed up pageloads (no guessing of encoding needed) and prevent issues with incorrect character encodings being assumed)~~
- `<link rel="shortcut icon" href="favicon.ico">` (the site is missing a favicon, that little 16x16 icon next to the site's title in your tab bar, and it's generally a nice thing to have)
- Also, the text looks a bit jumbled in Internet Explorer versions older than 9.

**Comment by codykrieger** [comment]
Fixed a couple of those things in 9f2097e02. Feel free to make a favicon, and I'll add it if it looks good. ;)

Were you looking at the site in IE9 + compatibility mode? Or actual copies of IE7/8?

**Comment by nickserv** [comment]
Remember to check that you're actually sending your files with the utf-8 encoding.

Also, I'm pretty bad with icon design, but I'm decent at Photoshop/Gimp. I was thinking about just taking the SSE logo and putting it over a simple rounded background. I could try to make one, and you can have someone else tweak it if you want.

And I was using [Adobe Browser Lab](https://browserlab.adobe.com/en-us/index.html), which should be using actual versions of IE7 and IE8. I can screenshot it if you want.

**Comment by nickserv** [comment]
Is there a vector version of the large SSE logo (logo-white.png) I could use?

**Comment by codykrieger** [comment]
Errrr there's an enormous .png somewhere but I think Chowder might have a vector/EPS version. /cc @chriscowdery
