### ISSUE TITLE
Can't create event with duplicate name

### ISSUE THREAD

**Issue by derekerdmann** [rit-sse/wtf#33]
Steps to reproduce:
1. Create an event
2. Create an event with the same name

The second event fails to save, and the following error is displayed:

> **1 error prohibited this event from being saved:**
> Name has already been taken

This may be by design, but it doesn't make sense for SSE events.  We often run the same event multiple times (like review sessions), and the uniqueness of the event should be indicated by a combination of title, date, and time.

**Comment by chrisbenti** [comment]
See [event.rb](https://github.com/rit-sse/wtf/blob/master/app/models/event.rb), line 5

```
validates_uniqueness_of :name
```

**Comment by derekerdmann** [comment]
I figured it was something like that, but I was trying to get it running on Windows first. When I get gallifrey back up, I'll fix it and submit a pull request.
