### ISSUE TITLE
Event highlights for google tv

### ISSUE THREAD

**Issue by ghost** [rit-sse/wtf#39]
Todd has requested that the google tv be able to show a full screen slide for an event within 24 hours of the event occurring.

For now this could done by providing an image upload section on the event edit page and displaying said image in the google tv rotation.  (Note that there currently is an image upload field on the events page but it may or may not work)

**Comment by wyantb** [comment]
In theory, there's no reason the file upload shouldn't work.  If you want to use S3, follow the instructions in this file:

https://github.com/rit-sse/wtf/blob/master/config/fog_credentials.rb

If you don't feel like going through that pain, you could also upload files to the local file system.  This should also work.  But, it's disabled by default in production.  See the logic here:

https://github.com/rit-sse/wtf/blob/master/config/initializers/carrierwave.rb

**Comment by weswigham** [comment]
I can confirm that the image upload field at the very least seems to work in development.
