### ISSUE TITLE
Add ability to nest pages and find them at the root

### ISSUE THREAD

**Issue by codykrieger** [rit-sse/wtf#4]
e.g. ability to have urls like:

/randompage
/somepage/asdfpage/blahpage/asdf

Instead of needing to have /pages or /modulename in front of the page slugs.

Can probably move this from Rapture or previous CMSes of mine.

**Comment by ghost** [comment]
The page model now uses the ancestry gem so we get things like "page.children", etc.
All the routing and nesting logic still needs to be implemented

**Comment by codykrieger** [comment]
I can move over some of my existing logic that does that in a little while.

**Comment by crhossen** [comment]
Could Sean and Cody please break this into smaller tasks and make it happen‽

**Comment by codykrieger** [comment]
DONE!
