### ISSUE TITLE
Blog platform

### ISSUE THREAD

**Issue by ghost** [rit-sse/wtf#40]
I have received a request for the ability to have multiple basic blog like pages on the site.  I don't remember the exact use case for these; see Dorrene for more information.

I suspect we don't need anything fancy to start, just basic pages with blog posts, no need for comments, etc.

**Comment by weswigham** [comment]
![blog_layout](https://f.cloud.github.com/assets/2932786/255639/505061a8-8c12-11e2-90a8-0d9e473a4f9b.png)
Was wondering if something like this would be okay (for page layout); would appreciate feedback on the layout before I go about coding it (Also weather it should be a new template under "Pages" or its own system).

**Comment by ghost** [comment]
I'd drop the side shadow images and just keep the content aligned in the center like the rest of the pages do.  Otherwise it looks good.

Its probably best to make this a layout in the pages system (you'd only need one side bar content in that case as people can add more if they want to).  I need to think about the best way to link the page to the blog articles themselves...  I'll get back to you on that later today.  It may require a few changes to the current pages design.

**Comment by derekerdmann** [comment]
Bump. We need some kind of news/blog/press release capability so we can publicize the things we're working on or have done. Definitely agree that we don't need a commenting system.

**Comment by 7imbrook** [comment]
Consider it moved to the top of the list for new features.

**Comment by kristenmills** [comment]
I can work on this if no one else is.

**Comment by 7imbrook** [comment]
I assigned the issue to you. Let me know if you need any help with anything.

**Comment by kristenmills** [comment]
Closing this because crazy train
