### ISSUE TITLE
Create an SSEDAP Gem

### ISSUE THREAD

**Issue by ghost** [rit-sse/wtf#6]
Create a gem to easily (at a minimum) send authentication requests and retrieve role metadata.
Perhaps use HTTParty for requests?

**Comment by codykrieger** [comment]
@destroyerdust still interested in this?

**Comment by destroyerdust** [comment]
@codykrieger Yup, I'm still interested in this. Tomorrow after my 362 class I'll work on it. When are you free so we can go over SSEDAP and ruby geming? (I'll look up stuff for how to make gems n shit tomorrow prior to meeting up with you)

**Comment by codykrieger** [comment]
I'm free tomorrow from 2-4 and Thursday after 6.

**Comment by destroyerdust** [comment]
Thursday after 6 would be better, I'm in chem lab from 2-5 tomorrow. I'll take tomorrow to research everything I need for Thursday.

**Comment by codykrieger** [comment]
Right on.

**Comment by codykrieger** [comment]
Being worked on: [ssedap-client](/rit-sse/ssedap-client).
