### ISSUE TITLE
Deploy script fails if a different user previously started the server

### ISSUE THREAD

**Issue by weswigham** [rit-sse/wtf#68]
Whoever uses the deploy script owns the unicorn processes, this is a problem, since other users can't stop that process without sudo'ing a kill (on the server itself). 

Also, something us causing unicorn processes to duplicate, sometimes. I noticed we had 3 separate pools of unicorn workers running... (owned by different users, mind you)

**Comment by 7imbrook** [comment]
"Also, something us causing unicorn processes to duplicate, sometimes. I noticed we had 3 separate pools of unicorn workers running... (owned by different users, mind you)"

We also have different services running on the server. If we set it up to use a deploy user, we can user are own accounts to run as deploy. Or we can add a script too change ownership during deploy.

**Comment by weswigham** [comment]
"Or we can add a script too change ownership during deploy. "
Yes, for sure. We should also make the deploy script redeploy WTF, QDB, and /go/, since they are all 'the SSE website' even though they're not the same repo.

**Comment by 7imbrook** [comment]
We should keep them separate because they are different services on the
server. They run and go down separately.

On Sunday, November 17, 2013, Wesley Wigham wrote:

> "Or we can add a script too change ownership during deploy. "
> Yes, for sure. We should also make the deploy script redeploy WTF, QDB,
> and /go/, since they are all 'the SSE website' even though they're not the
> same repo.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rit-sse/wtf/issues/68#issuecomment-28648563
> .

## 

~Michael Timbrook

**Comment by weswigham** [comment]
> We should keep them separate because they are different services on the
server. They run and go down separately.

No more!
