### ISSUE TITLE
https:// and http:// domains not seen as the same domain by browsers

### ISSUE THREAD

**Issue by weswigham** [rit-sse/wtf#69]
Which is why the post/get requests involving the orbiters to the SSL-secured part of the site form the non-SSL homepage fail on production (i.e. the orbiter). The server (correctly) returns a 302 redirect, but the browser refuses to follow it since it's on a 'different' domain. 

We could fix this by enabling cross-domain resource sharing between the two, I believe, (`Access-Control-Allow-Origin: http://hostname.com` from the SSL pages) in our response headers; alternatively, we can hardcode the queries to use https://, but then they break in development...

**Comment by 7imbrook** [comment]
Have you switched over to submitting the orbital updates to an admin route?

**Comment by weswigham** [comment]
Yes
