### ISSUE TITLE
http://sse.se.rit.edu/events/.ical displays the election page?

### ISSUE THREAD

**Issue by derekerdmann** [rit-sse/wtf#72]
1. Visit http://sse.se.rit.edu/events/.ical
2. The page for the last primary officer election is displayed

What?

**Comment by derekerdmann** [comment]
It looks like you can get to the page if you use any string that begins with a dot after "/events/", like http://sse.se.rit.edu/events/.derp

**Comment by weswigham** [comment]
Fixed in live - someone was using the slug 'events' for the voting page from last year - for some reason. Rails was just matching the dynamic pages as closely as it could.

I was told to blame @chrisbenti for you.

**Comment by chrisbenti** [comment]
Not going to lie, if this was my fault (it probably was) I have no idea how I did it. GitHub: Tracking my SSE sins for all time.
