### ISSUE TITLE
Define Roles and Permissions

### ISSUE THREAD

**Issue by crhossen** [rit-sse/wtf#9]
Users can have multiple roles and roles have multiple permissions.

**Comment by codykrieger** [comment]
The way we had worked it out before was that users have a single role, but the roles are hierarchical (e.g. higher level roles have all permissions of lower level roles).

To start, we have:
- Admin - These folks have **ultimate control** and can administer any aspect of the site and SSEDAP. Admins would be President, VPs, and Technology.
- Officer - Can add/edit content on the site.
- Member - Can log in and have access to whatever it is that members are going to do.

I think that's pretty much it for R1.

**Comment by codykrieger** [comment]
CanCan reference: https://github.com/ryanb/cancan#readme
